excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://elmtown.github.io
title: Elm Town
email: 
author: Murphy Randle
description: A podcast about Elm and its people
paginate: 50
google_analytics: 